version: "3.9"

services:
  ngrok:
    container_name: ngrok
    image: ngrok/ngrok:latest
    ports:
      - 80:4040
    volumes:
      - ./ngrok/ngrok.yaml:/etc/ngrok.yaml
    command:
      - start
      - --all
      - --config
      - /etc/ngrok.yaml
    restart: unless-stopped
    networks:
      - devops

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: ${VAULT_ADDR}
      VAULT_API_ADDR: ${VAULT_ADDR}
      VAULT_CACERT: /vault/config/ssl/vault.crt
    volumes:
      - ./vault:/vault/file
      - ./vault:/vault/config
      - ./vault/script:/home/vault/
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/config.hcl
    healthcheck:
      retries: 5
    restart: unless-stopped
    networks:
      - devops

  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
    restart: unless-stopped
    networks:
      - devops

networks:
  devops: